### ISSUE TITLE
uhhhhh

### ISSUE THREAD

**Issue by TheStinkern** [evanpacini/ordered-dithering-shader#5]
how do i even fix this?
![image](https://github.com/user-attachments/assets/a2123262-3b9e-41f4-9ae1-7fa14937ad15)

**Comment by evanpacini** [comment]
Hmmm, hadn't touched this repo in a while, might've left it in a broken state. Just pushed some changes, and I have no issues with it atm, so maybe pull the changes and see if it works for you now?

**Comment by TheStinkern** [comment]
I'll check later

**Comment by TheStinkern** [comment]
its working now, thanks
